# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
dist: bionic
addons:
  apt:
    packages:
      - python3-pip
notifications:
  email: false
jobs:
  allow_failures:
    - julia: nightly
  include:
    - stage: "docs"
      julia: 1.3
      os: linux
      script:
        - python3 --version
        - pip3 install --user matplotlib
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        - julia --project=docs/ -e 'include(joinpath("docs", "make.jl"))' --color=yes
      after_success: skip
